### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '[imagent-data-root]\\ILSVRC2012/val/n03131574/ILSVRC2012_val_00040407.JPEG'

### ISSUE THREAD

**Issue by xiaoweidao** [jiawangbai/DHTA-master#2]
Has anyone encountered this problem? Can you help me?

**Comment by zzxihuanheixiu** [comment]
我也遇到了这个问题，是不是因为作者没有给出数据集啊？

**Comment by xiaoweidao** [comment]
> 我也遇到了这个问题，是不是因为作者没有给出数据集啊？

兄弟，解决了的话滴我一下

**Comment by zzxihuanheixiu** [comment]
妈耶，作都不回复，我看没戏了



---Original---
From: ***@***.***&gt;
Date: Sun, May 23, 2021 19:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jiawangbai/DHTA-master] FileNotFoundError: [Errno 2] No such file or directory: '[imagent-data-root]\\ILSVRC2012/val/n03131574/ILSVRC2012_val_00040407.JPEG' (#2)




  
我也遇到了这个问题，是不是因为作者没有给出数据集啊？
  
兄弟，解决了的话滴我一下

**Comment by yechao-zhang** [comment]
改代码就可以了吧，数据集什么的也没必要和他的一样吧

**Comment by jiawangbai** [comment]
不好意思，今天才看到。需要你自己下载imagenet数据集，然后把data目录下三个.txt文件中对应的imagenet数据集路径，改为你的机器上所保存的imagenet数据集路径，也就是：

ILSVRC2012/val/n02219486/ILSVRC2012_val_00021157.JPEG -> your_imagenet_path/val/n02219486/ILSVRC2012_val_00021157.JPEG

即可直接跑通我们的代码。

**Comment by zzxihuanheixiu** [comment]
OK了，谢谢大佬！



---Original---
From: ***@***.***&gt;
Date: Sat, May 29, 2021 18:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jiawangbai/DHTA-master] FileNotFoundError: [Errno 2] No such file or directory: '[imagent-data-root]\\ILSVRC2012/val/n03131574/ILSVRC2012_val_00040407.JPEG' (#2)




 
不好意思，今天才看到。需要你自己下载imagenet数据集，然后把data目录下三个.txt文件中对应的imagenet数据集路径，改为你的机器上所保存的imagenet数据集路径，也就是：
 
ILSVRC2012/val/n02219486/ILSVRC2012_val_00021157.JPEG -&gt; your_imagenet_path/val/n02219486/ILSVRC2012_val_00021157.JPEG
 
即可直接跑通我们的代码。
